# Generated by Django 5.1.1 on 2024-10-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management', '0002_analysisrecord_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lane_occupancy', models.TextField(default=dict)),
                ('traffic_capacity', models.TextField(default=dict)),
                ('saturation', models.FloatField(default=0.0)),
                ('flow_matrix', models.TextField(default=dict)),
                ('main_directions', models.TextField(default=list)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('speed_distribution', models.TextField(default=dict)),
                ('passage_times', models.TextField(default=dict)),
                ('bottleneck_points', models.TextField(default=list)),
                ('congestion_areas', models.TextField(default=list)),
                ('abnormal_events', models.TextField(default=list)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management.location')),
            ],
            options={
                'db_table': 'traffic_analysis_records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
